CC = g++
FILES = main.cpp utils.cpp Ant.cpp Item.cpp
LINKS = -Wall -lsfml-graphics -lsfml-window -lsfml-system -std=c++11 -O2

all:
	$(CC) -o formigas $(FILES) $(LINKS) && ./formigas

clean:
	rm formigas
